name: Push to Upstream

on:
  push:
    branches:
      - main

jobs:
  push_to_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "박도륜"
          git config --global user.email "88328436+ryxxn@users.noreply.github.com"

      - name: Push to upstream
        env:
          UPSTREAM_TOKEN: ${{ secrets.UPSTREAM_TOKEN }}
        run: |
          git push https://ryxxn:${UPSTREAM_TOKEN}@github.com/ryxxn/weppstore-fe.git main
